prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/shared_components/navigation/lists/desktop_navigation_menu.sql
@@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@@application/shared_components/navigation/lists/administrator.sql
@@application/shared_components/navigation/lists/administrator_002.sql
@@application/shared_components/files/app_icon_svg.sql
@@application/shared_components/files/app_icon_css.sql
@@application/shared_components/files/logo_for_apex_jpg.sql
@@application/shared_components/files/beef_kachi_jpg.sql
@@application/shared_components/files/mutton_kachi_jpg.sql
@@application/shared_components/files/pizza_jpg.sql
@@application/shared_components/files/login_page_image_for_apex_jpg.sql
@@application/shared_components/files/login_small_page_image_for_apex_jpg.sql
@@application/shared_components/files/mutton_curry_image_jpg.sql
@@application/shared_components/files/nur_jpg.sql
@@application/shared_components/files/oli_jpg.sql
@@application/shared_components/files/shiblu_jpg.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_items/userfname.sql
@@application/shared_components/logic/application_items/username.sql
@@application/shared_components/logic/application_items/usern_info_id.sql
@@application/shared_components/logic/application_computations/userfname.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/employee_name_lov.sql
@@application/shared_components/user_interface/lovs/food_menu_name.sql
@@application/shared_components/user_interface/lovs/guest_name_guest_id.sql
@@application/shared_components/user_interface/lovs/login_remember_username.sql
@@application/shared_components/user_interface/lovs/payment_mode.sql
@@application/shared_components/user_interface/lovs/purchase_item_name.sql
@@application/shared_components/user_interface/lovs/supplier_name.sql
@@application/shared_components/user_interface/lovs/supplier_name_and_id.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbs/supplier_report.sql
@@application/shared_components/navigation/breadcrumbs/food_menu_report.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/page/left_side_column.sql
@@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@@application/shared_components/user_interface/templates/page/login.sql
@@application/shared_components/user_interface/templates/page/master_detail.sql
@@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@@application/shared_components/user_interface/templates/page/modal_dialog.sql
@@application/shared_components/user_interface/templates/page/right_side_column.sql
@@application/shared_components/user_interface/templates/page/standard.sql
@@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@@application/shared_components/user_interface/templates/button/icon.sql
@@application/shared_components/user_interface/templates/button/text.sql
@@application/shared_components/user_interface/templates/button/text_with_icon.sql
@@application/shared_components/user_interface/templates/region/alert.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@@application/shared_components/user_interface/templates/region/buttons_container.sql
@@application/shared_components/user_interface/templates/region/cards_container.sql
@@application/shared_components/user_interface/templates/region/carousel_container.sql
@@application/shared_components/user_interface/templates/region/collapsible.sql
@@application/shared_components/user_interface/templates/region/content_block.sql
@@application/shared_components/user_interface/templates/region/hero.sql
@@application/shared_components/user_interface/templates/region/inline_dialog.sql
@@application/shared_components/user_interface/templates/region/inline_popup.sql
@@application/shared_components/user_interface/templates/region/interactive_report.sql
@@application/shared_components/user_interface/templates/region/login.sql
@@application/shared_components/user_interface/templates/region/standard.sql
@@application/shared_components/user_interface/templates/region/tabs_container.sql
@@application/shared_components/user_interface/templates/region/title_bar.sql
@@application/shared_components/user_interface/templates/region/wizard_container.sql
@@application/shared_components/user_interface/templates/list/badge_list.sql
@@application/shared_components/user_interface/templates/list/cards.sql
@@application/shared_components/user_interface/templates/list/links_list.sql
@@application/shared_components/user_interface/templates/list/media_list.sql
@@application/shared_components/user_interface/templates/list/menu_bar.sql
@@application/shared_components/user_interface/templates/list/menu_popup.sql
@@application/shared_components/user_interface/templates/list/navigation_bar.sql
@@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/tabs.sql
@@application/shared_components/user_interface/templates/list/top_navigation_mega_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@@application/shared_components/user_interface/templates/list/wizard_progress.sql
@@application/shared_components/user_interface/templates/report/alerts.sql
@@application/shared_components/user_interface/templates/report/badge_list.sql
@@application/shared_components/user_interface/templates/report/cards.sql
@@application/shared_components/user_interface/templates/report/comments.sql
@@application/shared_components/user_interface/templates/report/content_row.sql
@@application/shared_components/user_interface/templates/report/contextual_info.sql
@@application/shared_components/user_interface/templates/report/media_list.sql
@@application/shared_components/user_interface/templates/report/search_results.sql
@@application/shared_components/user_interface/templates/report/standard.sql
@@application/shared_components/user_interface/templates/report/timeline.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@@application/shared_components/user_interface/templates/label/hidden.sql
@@application/shared_components/user_interface/templates/label/optional.sql
@@application/shared_components/user_interface/templates/label/optional_above.sql
@@application/shared_components/user_interface/templates/label/optional_floating.sql
@@application/shared_components/user_interface/templates/label/required.sql
@@application/shared_components/user_interface/templates/label/required_above.sql
@@application/shared_components/user_interface/templates/label/required_floating.sql
@@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/templates/calendar/calendar.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@@application/shared_components/reports/report_queries/daily_sales_report.sql
@@application/shared_components/reports/report_queries/invoice_wise_sales_report.sql
@@application/shared_components/reports/report_queries/date_for_print.sql
@@application/shared_components/reports/report_queries/guest_point_earning_information.sql
@@application/shared_components/reports/report_queries/top_ten_past_moving_food_menu.sql
@@application/shared_components/reports/report_queries/income_wise_food_menu_rank.sql
@@application/shared_components/reports/report_queries/supplier_contact_details.sql
@@application/shared_components/reports/report_queries/purchasing_item_information.sql
@@application/shared_components/reports/report_queries/supplier_wise_purchase_summary2.sql
@@application/shared_components/reports/report_queries/supplier_current_due.sql
@@application/shared_components/reports/report_queries/period_wise_sales_report.sql
@@application/shared_components/reports/report_queries/bill_report.sql
@@application/shared_components/reports/report_queries/invoice_wise_purchase_report.sql
@@application/shared_components/reports/report_queries/daily_purchase_report.sql
@@application/shared_components/reports/report_queries/period_wise_purchase_report.sql
@@application/shared_components/reports/report_queries/period_wise_purchase_summary.sql
@@application/shared_components/reports/report_queries/supplier_form_report.sql
@@application/shared_components/reports/report_queries/guest_form_report.sql
@@application/shared_components/reports/report_queries/business_status.sql
@@application/shared_components/reports/report_queries/period_wise_sales_summary.sql
@@application/shared_components/reports/report_queries/empoyee_form_report.sql
@@application/shared_components/reports/report_queries/print_last_bill.sql
@@application/shared_components/reports/report_queries/business_status_with_format_mask.sql
@@application/shared_components/reports/report_layouts/guest_point_earnig_inforamtion.sql
@@application/shared_components/reports/report_layouts/supplier_contact_details.sql
@@application/shared_components/reports/report_layouts/purchasing_item_information.sql
@@application/shared_components/reports/report_layouts/supplier_wise_purchase_summary1.sql
@@application/shared_components/reports/report_layouts/supplier_wise_current_due.sql
@@application/shared_components/reports/report_layouts/bill.sql
@@application/shared_components/reports/report_layouts/daily_purchase_report_layout.sql
@@application/shared_components/reports/report_layouts/invoice_wise_purchase_report.sql
@@application/shared_components/reports/report_layouts/period_wise_purchase_report.sql
@@application/shared_components/reports/report_layouts/period_wise_purchase_summary.sql
@@application/shared_components/reports/report_layouts/suppllier_form_report.sql
@@application/shared_components/reports/report_layouts/guest_form_report.sql
@@application/shared_components/reports/report_layouts/invoice_wise_sales_report.sql
@@application/shared_components/reports/report_layouts/invoice_wise_sales_repo1rt.sql
@@application/shared_components/reports/report_layouts/daily_sales_report_layout1.sql
@@application/shared_components/reports/report_layouts/daily_sales_report_layout.sql
@@application/shared_components/reports/report_layouts/period_wise_sales_report1.sql
@@application/shared_components/reports/report_layouts/period_wise_sales_report.sql
@@application/shared_components/reports/report_layouts/business_status_final.sql
@@application/shared_components/reports/report_layouts/invoice_wise_purchase_report1.sql
@@application/shared_components/reports/report_layouts/daily_purchase_report_layout1.sql
@@application/shared_components/reports/report_layouts/period_wise_purchase_report1.sql
@@application/shared_components/reports/report_layouts/period_wise_purchase_summary1.sql
@@application/shared_components/reports/report_layouts/period_wise_sales_summary.sql
@@application/shared_components/reports/report_layouts/employee_contact_detail.sql
@@application/shared_components/reports/report_layouts/emplyee_form_report.sql
@@application/shared_components/reports/report_layouts/business_status_with_format_mask.sql
@@application/shared_components/reports/report_layouts/bunsiness_status_with_formatmask.sql
@@application/shared_components/reports/report_layouts/supplier_wise_current_due_final.sql
@@application/shared_components/reports/report_layouts/supplier_wise_purchase_summary_final.sql
@@application/shared_components/security/authentications/application_express_accounts.sql
@@application/shared_components/security/authentications/user_authentication.sql
@@application/user_interfaces.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00006.sql
@@application/pages/page_00007.sql
@@application/pages/page_00008.sql
@@application/pages/page_00009.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00015.sql
@@application/pages/page_00016.sql
@@application/pages/page_00017.sql
@@application/pages/page_00018.sql
@@application/pages/page_00019.sql
@@application/pages/page_00020.sql
@@application/pages/page_00021.sql
@@application/pages/page_00022.sql
@@application/pages/page_00023.sql
@@application/pages/page_00024.sql
@@application/pages/page_00025.sql
@@application/pages/page_00026.sql
@@application/pages/page_00027.sql
@@application/pages/page_00028.sql
@@application/pages/page_00029.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_00033.sql
@@application/pages/page_00034.sql
@@application/pages/page_00035.sql
@@application/pages/page_00036.sql
@@application/pages/page_00037.sql
@@application/pages/page_00038.sql
@@application/pages/page_00039.sql
@@application/pages/page_00040.sql
@@application/pages/page_00041.sql
@@application/pages/page_00042.sql
@@application/pages/page_00043.sql
@@application/pages/page_00044.sql
@@application/pages/page_00045.sql
@@application/pages/page_00046.sql
@@application/pages/page_00047.sql
@@application/pages/page_00048.sql
@@application/pages/page_00049.sql
@@application/pages/page_00050.sql
@@application/pages/page_00051.sql
@@application/pages/page_00052.sql
@@application/pages/page_00053.sql
@@application/pages/page_00054.sql
@@application/pages/page_00055.sql
@@application/pages/page_00056.sql
@@application/pages/page_00057.sql
@@application/pages/page_00058.sql
@@application/pages/page_00059.sql
@@application/pages/page_00060.sql
@@application/pages/page_00061.sql
@@application/pages/page_00062.sql
@@application/pages/page_00063.sql
@@application/pages/page_00064.sql
@@application/pages/page_00065.sql
@@application/pages/page_00066.sql
@@application/pages/page_00067.sql
@@application/pages/page_00068.sql
@@application/pages/page_00069.sql
@@application/pages/page_00070.sql
@@application/pages/page_00071.sql
@@application/pages/page_00072.sql
@@application/pages/page_00073.sql
@@application/pages/page_00074.sql
@@application/pages/page_00075.sql
@@application/pages/page_00076.sql
@@application/pages/page_00077.sql
@@application/pages/page_00078.sql
@@application/pages/page_00079.sql
@@application/pages/page_00080.sql
@@application/pages/page_00081.sql
@@application/pages/page_00082.sql
@@application/pages/page_00083.sql
@@application/pages/page_00084.sql
@@application/pages/page_00086.sql
@@application/pages/page_00087.sql
@@application/pages/page_00088.sql
@@application/pages/page_00089.sql
@@application/pages/page_09999.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
