prompt --application/pages/page_00043
begin
--   Manifest
--     PAGE: 00043
--   Manifest End
wwv_flow_api.component_begin (
 p_version_yyyy_mm_dd=>'2021.10.15'
,p_release=>'21.2.4'
,p_default_workspace_id=>20952813001415487158
,p_default_application_id=>141546
,p_default_id_offset=>0
,p_default_owner=>'WKSP_DDD451261366WORKSPACE'
);
wwv_flow_api.create_page(
 p_id=>43
,p_user_interface_id=>wwv_flow_api.id(21352811266698583054)
,p_name=>'Invoice Wise Sales Report'
,p_alias=>'INVOICE-WISE-SALES-REPORT'
,p_step_title=>'Invoice Wise Sales Report'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'OLIURK2@GMAIL.COM'
,p_last_upd_yyyymmddhh24miss=>'20210917201635'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(28632200753585954535)
,p_plug_name=>'Search'
,p_region_template_options=>'t-Region--removeHeader js-removeLandmark:t-Region--textContent:t-Region--scrollBody:t-Form--xlarge:t-Form--stretchInputs'
,p_plug_template=>wwv_flow_api.id(21352721678779582998)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_item_display_point=>'BELOW'
,p_plug_source=>'<h1 style="color: #3333ff;"><center>   Invoice-Wise Sales Report   <center> </h1>'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(31365168061968775250)
,p_plug_name=>'Invoice Wise Sales Report'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(21352719760576582997)
,p_plug_display_sequence=>60
,p_include_in_reg_disp_sel_yn=>'Y'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select order_master.invoice,(select guest_name from guest where guest_id = order_master.guest_id) guest_name,order_date,TOTAL_PRICE-AFTER_DISCOUNT Discount,GRANT_TOTAL-AFTER_DISCOUNT vat, GRANT_TOTAL,',
'      (food_menu_name) Food_menu_name,order_detail.quantity,order_detail.price, order_detail.quantity*order_detail.price unit_tatal',
'from   order_master,order_detail,food_menu',
'where  order_detail.invoice = order_master.invoice',
'and  order_detail.food_menu_id=food_menu.food_menu_id',
'and  order_master.invoice= :P43_INVOICE;',
''))
,p_plug_source_type=>'NATIVE_IR'
,p_ajax_items_to_submit=>'P43_INVOICE'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_units=>'INCHES'
,p_prn_paper_size=>'LETTER'
,p_prn_width=>11
,p_prn_height=>8.5
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header=>'Invoice Wise Sales Report'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#EEEEEE'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'bold'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#FFFFFF'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
,p_prn_border_color=>'#666666'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(31798080751579172301)
,p_max_row_count=>'1000000'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_lazy_loading=>false
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:XLSX:PDF'
,p_enable_mail_download=>'Y'
,p_owner=>'OLIURK2@GMAIL.COM'
,p_internal_uid=>31798080751579172301
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798080842269172302)
,p_db_column_name=>'INVOICE'
,p_display_order=>10
,p_column_identifier=>'A'
,p_column_label=>'Invoice'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798080934315172303)
,p_db_column_name=>'GUEST_NAME'
,p_display_order=>20
,p_column_identifier=>'B'
,p_column_label=>'Guest Name'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081037057172304)
,p_db_column_name=>'ORDER_DATE'
,p_display_order=>30
,p_column_identifier=>'C'
,p_column_label=>'Order Date'
,p_column_type=>'DATE'
,p_column_alignment=>'CENTER'
,p_tz_dependent=>'N'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081238195172306)
,p_db_column_name=>'QUANTITY'
,p_display_order=>50
,p_column_identifier=>'E'
,p_column_label=>'Quantity'
,p_column_type=>'NUMBER'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081301168172307)
,p_db_column_name=>'PRICE'
,p_display_order=>60
,p_column_identifier=>'F'
,p_column_label=>'Price'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'99,99,99,999.99'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081465877172308)
,p_db_column_name=>'UNIT_TATAL'
,p_display_order=>70
,p_column_identifier=>'G'
,p_column_label=>'Unit Tatal'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'99,99,99,999.99'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081730988172311)
,p_db_column_name=>'VAT'
,p_display_order=>100
,p_column_identifier=>'H'
,p_column_label=>'Vat'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798081803969172312)
,p_db_column_name=>'DISCOUNT'
,p_display_order=>110
,p_column_identifier=>'I'
,p_column_label=>'Discount'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798082011537172314)
,p_db_column_name=>'GRANT_TOTAL'
,p_display_order=>120
,p_column_identifier=>'K'
,p_column_label=>'Paid Amount'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(31798082122500172315)
,p_db_column_name=>'FOOD_MENU_NAME'
,p_display_order=>130
,p_column_identifier=>'L'
,p_column_label=>'Food Menu Name'
,p_column_type=>'STRING'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(31799658748409580707)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'317996588'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'INVOICE:GUEST_NAME:ORDER_DATE:FOOD_MENU_NAME:QUANTITY:PRICE:UNIT_TATAL:VAT:DISCOUNT:GRANT_TOTAL'
,p_break_on=>'INVOICE:ORDER_DATE:GUEST_NAME:DISCOUNT:VAT:GRANT_TOTAL'
,p_break_enabled_on=>'INVOICE:ORDER_DATE:GUEST_NAME:DISCOUNT:VAT:GRANT_TOTAL'
,p_sum_columns_on_break=>'UNIT_TATAL'
);
wwv_flow_api.create_page_button(
 p_id=>wwv_flow_api.id(31798082341458172317)
,p_button_sequence=>30
,p_button_plug_id=>wwv_flow_api.id(28632200753585954535)
,p_button_name=>'Download'
,p_button_action=>'DEFINED_BY_DA'
,p_button_template_options=>'#DEFAULT#:t-Button--gapTop'
,p_button_template_id=>wwv_flow_api.id(21352786737075583034)
,p_button_is_hot=>'Y'
,p_button_image_alt=>'Print'
,p_warn_on_unsaved_changes=>null
,p_grid_new_row=>'N'
,p_grid_column_span=>2
,p_grid_column=>9
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(28632200851381954536)
,p_name=>'P43_INVOICE'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(28632200753585954535)
,p_prompt=>'Invoice'
,p_display_as=>'NATIVE_POPUP_LOV'
,p_lov=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select invoice',
'from    order_master',
'order   by to_number(invoice,''999999'') desc;'))
,p_cSize=>30
,p_colspan=>2
,p_grid_column=>6
,p_grid_label_column_span=>0
,p_field_template=>wwv_flow_api.id(21352784098317583033)
,p_item_template_options=>'#DEFAULT#:t-Form-fieldContainer--stretchInputs'
,p_lov_display_extra=>'NO'
,p_encrypt_session_state_yn=>'N'
,p_attribute_01=>'POPUP'
,p_attribute_02=>'FIRST_ROWSET'
,p_attribute_03=>'N'
,p_attribute_04=>'N'
,p_attribute_05=>'N'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(28632200920162954537)
,p_name=>'refresh_region'
,p_event_sequence=>10
,p_triggering_element_type=>'ITEM'
,p_triggering_element=>'P43_INVOICE'
,p_condition_element=>'P43_INVOICE'
,p_triggering_condition_type=>'NOT_NULL'
,p_bind_type=>'bind'
,p_bind_event_type=>'change'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(28834113818117499617)
,p_event_id=>wwv_flow_api.id(28632200920162954537)
,p_event_result=>'TRUE'
,p_action_sequence=>30
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_REFRESH'
,p_affected_elements_type=>'REGION'
,p_affected_region_id=>wwv_flow_api.id(31365168061968775250)
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(28632201975335954547)
,p_name=>'Invoice_clear'
,p_event_sequence=>20
,p_bind_type=>'bind'
,p_bind_event_type=>'ready'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(28632202040782954548)
,p_event_id=>wwv_flow_api.id(28632201975335954547)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_CLEAR'
,p_affected_elements_type=>'ITEM'
,p_affected_elements=>'P43_INVOICE'
);
wwv_flow_api.create_page_da_event(
 p_id=>wwv_flow_api.id(34807175615793750901)
,p_name=>'Print'
,p_event_sequence=>30
,p_triggering_element_type=>'BUTTON'
,p_triggering_button_id=>wwv_flow_api.id(31798082341458172317)
,p_bind_type=>'bind'
,p_bind_event_type=>'click'
);
wwv_flow_api.create_page_da_action(
 p_id=>wwv_flow_api.id(34807175776487750902)
,p_event_id=>wwv_flow_api.id(34807175615793750901)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'window.open(''f?p=&APP_ID.:0:&SESSION.:PRINT_REPORT=Invoice_wise_sales_report'',''_blank'');'
);
wwv_flow_api.component_end;
end;
/
